#10、高级排序
#如果希望用特定的方式排序(python默认的排序方式是升序排列)，可以使用compare(x,y)的形式定义比较参数
#compare(x,y)会在x>y时返回正数，在x<y时返回负数，在x=y时返回0,cmp(函数在python3中已经舍弃)
#sort方法还有另外俩个可选参数key和reverse，如果要使用，就要通过名字来指定(关键字参数)
#key参数必须提供一个在排序过程中使用的函数，为每个元素创建一个键，所有元素按照键来排序(例如长度)
x=["c","cccc","cc","ccccccc"]
x.sort(key=len)
print(x)
#另一个关键字参数reveser是简单的布尔值，来指明列表是否需要反向排序
x1=[1,4,7,8,5,2,3,6,9]
x1.sort(reverse=True)
print(x1)
#以上三个参数都可以用于sorted函数