#3、分片赋值
#修改
name=list('perl')
name[2:]=list('ar')
print(name)
#可以替换原长度
name=list('perl')
name[1:]=list('ython')
print(name)
#可以在不替换任何元素的情况下插入新元素
number=[1,5,5]
number[1:1]=[2,3,4]
print(number)
#可以删除序列
number=[1,2,3,4,5,7,8,9]
number[1:2]=[]
print(number)

#九、列表方法
#1、append方法(用于在列表末尾追加新的对象)
list1=[1,2,3]
list1.append(4)
print(list1)
#2、count方法统计某个元素在列表中出现的次数
list2=[1,1,1,2,3]
print(list2.count(1))
#3、extend方法可以在列表的末尾一次追加序列中的多个值，可以扩展多个序列(返回的序列是list3，而使用list3+list4会得到一个全新的序列，效率会比较低，分片操作也可以实现，不过可读性差)
list3=[1,2,3]
list4=[4,5,6]
list3.extend(list4)
print(list3)
#4、index方法用于从列表中找出某个值第一个匹配项的索引位置
print(list1.index(2))
#5、insert方法用于将对象插入到列表中,分片操作也可以实现，但是可读性较差
list1.insert(1,5)
print(list1)